### ISSUE TITLE
changer et afficher resultat du formulaire

### ISSUE THREAD

**Issue by KamiSamaKun** [czantoine/efrei-pokemon-go#1]
Bonjour, 
Merci pour votre projet :)
Mais comment changer le formulaire par celui que nous souhaitons afficher  mais aussi le résultat dans le fichier index.php ?

Merci bien à vous.

**Comment by czantoine** [comment]
Bonjour,

Pour changer le formulaire qui se trouve dans ajouter.html il faut ajouter le sien qui se trouve dans la balise <iframe>  .... </iframe>. 

Pour l'afficher dans  index.php il faut : 

- modifier le fichier script.js ( pour le tableau ) ou stat.js ( pour les pourcentages ). C'est le `jsonSource` ou vous allez appeler votre speadsheet. 
- modifier `var $horodateur = item.gsx$horodateur.$t;`

Je pense qu'il faudrait que je fasse une version moins personnel et améliorer la documentation.

J'ai crée ce nouveau [repo](https://github.com/czantoine/Pokemon-GO-Friend-Codes)

**Comment by KamiSamaKun** [comment]
Bonjour merci pour votre réponse votre projet est super j'aimerai intégrer votre projet sur mon site blog
si vous savez m'ajouter via Facebook ou me contacter en mp sur facebook.
https://www.facebook.com/narutospeed.pkmngobefr.3

Bien à vous.
